events {
    worker_connections 1024;
}

http {
    types {
        text/html                             html htm shtml;
        text/css                              css;
        text/xml                              xml;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        application/javascript                js;
        application/json                      json;
        application/atom+xml                  atom;
        application/rss+xml                   rss;
    }
    default_type application/octet-stream;

    server {
        listen 8000;
        server_name localhost;

        # Semua request API biasa
        location / {
            # Amankan request Preflight OPTIONS untuk CORS
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'https://frontend-belanjaan-vercel.app' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With, X-XSRF-TOKEN' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }

            add_header 'Access-Control-Allow-Origin' 'https://frontend-belanjaan-vercel.app' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            proxy_pass http://127.0.0.1:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Request WebSocket Reverb
        location /app {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 60s;
            proxy_connect_timeout 60s;
        }
    }
}
